import "./globals.css";
import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
// Providers
import { ClerkProvider } from "@clerk/nextjs";

const NotificationsProvider = dynamic(
  () => import("@/components/providers/NotificationsProvider")
);
const ModalProvider = dynamic(
  () => import("@/components/providers/ModalProvider")
);
const ThemeProvider = dynamic(
  () => import("@/components/providers/ThemeProvider")
);

const font = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "DRM",
  description: "Generated by Webranch team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ThemeProvider>
        <html lang="en">
          <body className={`${font.className} bg-bgColors-primary h-screen`}>
            <ModalProvider />
            <NotificationsProvider />
            {children}
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
