import "./globals.css";

import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
// Providers
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import ModalProvider from "@/components/providers/ModalProvider";
import NotificationsProvider from "@/components/providers/NotificationsProvider";

const font = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "DRM",
  description: "Generated by Webranch team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <ThemeProvider>
          <body className={`${font.className} bg-bgColors-primary h-screen`}>
            {children}
            <ModalProvider />
            <NotificationsProvider />
          </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  );
}
